version: '3.8'

networks:
  infra-consul:
    external: True
    name: infra-consul
  traefik-public:
    external: True

services:
  vault:
    image: ${IMAGE_REPO_ROOT}library/vault:1.5.4
    networks:
      - infra-consul
      - traefik-public
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_API_ADDR: http://vault:8200
      VAULT_TOKEN: mytoken
      VAULT_LOCAL_CONFIG: |
        {
          "backend": {
            "consul": {
              "address": "consul-client:8500",
              "advertise_addr": "http://consul-client:8300",
              "scheme": "http"
            }
          },
          "ui": true,
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h",
          "storage": {
            "consul": {
              "address": "consul-client:8500",
              "path": "vault/"
            }
          },
          "listener": {
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": 1
            }
          },
          "disable_mlock": 1
        }
    command: ["server"]
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.consul-server-bootstrap == true
        max_replicas_per_node: 1
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.http.routers.vault-http.rule=Host(`vault.${DOMAIN?Variable not set}`)
        - traefik.http.routers.vault-http.entrypoints=http
        - traefik.http.routers.vault-http.service=vault
        - traefik.http.routers.vault-https.rule=Host(`vault.${DOMAIN?Variable not set}`)
        - traefik.http.routers.vault-https.entrypoints=https
        - traefik.http.routers.vault-https.tls=ture
        - traefik.http.routers.vault-https.service=vault
        - traefik.http.services.vault.loadbalancer.server.port=8200

